networks:
  influx-network:
    name: influx-network

services:

  grafana:
    container_name: grafana
    image: grafana/grafana-oss:11.1.4
    ports:
      - 443:3000
    networks:
       - influx-network
    volumes:
      - ./grafana/data:/var/lib/grafana
      - ./grafana/etc/grafana.ini:/etc/grafana/grafana.ini
      - ./grafana/etc/auth.ini:/etc/grafana/auth.ini
    environment:
      - GF_PATHS_CONFIG/etc/grafana/grafana.ini,/etc/grafana/auth.ini

  influxdb:
    container_name: influxdb
    image: influxdb:2.7.10
    ports:
      - 8086:8086
    networks:
      - influx-network
    volumes:
      - ./influxdb/data:/var/lib/influxdb2
      - ./influxdb/config:/etc/influxdb
    environment:
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=$TOKEN
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=$INFLUXDB_PASSWORD
      - DOCKER_INFLUXDB_INIT_ORG=Siemens AG
      - DOCKER_INFLUXDB_INIT_BUCKET=demo

#  telegraf:
#    container_name: telegraf
#    image: telegraf:1.31.3
#    networks:
#      - influx-network
#    volumes:
#      - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf
#    environment:
#      - INFLUXDB_URL=http://influxdb:8086
#      - INFLUXDB_TOKEN=$TOKEN
#      - INFLUXDB_ORG=Siemens AG
#      - INFLUXDB_BUCKET=demo
#      - INFLUXDB_USERNAME=admin
#      - INFLUXDB_PASSWORD=$INFLUXDB_PASSWORD
#    depends_on:
#      - influxdb